### ISSUE TITLE
Close istance obj

### ISSUE THREAD

**Issue by Bobsilvio** [AnthonyBloomer/tmdbv3api#1]
How? close istance for call 2 time different methods?
example:
	
		search = tmdb.search('avatar')
		for movie in search:
			print movie.id

		similar = tmdb.similar('movie.id')
		for sim in similar()
			print sim.title

this show me error..
AttributeError: obj instance has no attribute 'title'

**Comment by AnthonyBloomer** [comment]
Hi Bobsilvio, you should pass movie.id in without the single quotes. You're getting the attribute error because the method isn't returning anything.

```
similar = tmdb.similar(movie.id):
  for sim in similar:
    print sim.title
```

**Comment by Bobsilvio** [comment]
yes sorry for code error..
so, no it's not the problem.. return it's ok(by print in your api). first obj not closed.

**Comment by AnthonyBloomer** [comment]
Try this to see if it solves your problem.

```
movie = self.tmdb.search("Avatar")
for l in movie:
     s = self.tmdb.similar(l.id)
     for i in s:
         print i.title
```

**Comment by Bobsilvio** [comment]
Not work.. i have integrated new call in api:
    def videos(self, id, page=1):
        result = self._call('movie/' + str(id) + '/videos', 'page=' + str(page))
        [self.data.append(obj(**res)) for res in result['results']]
        return self.data


this is my test.py
.....

from tmdbv3api import TMDb
tmdb = TMDb(api_key="keykey", debug=False, lang="it")


class Database(object):
	def __init__(self,Nomefilm):
		self.nomefilm = Nomefilm
	
	def test(self):
		movie = tmdb.search(self.nomefilm)
		for l in movie:
			s = tmdb.videos(l.id)
			for i in s:
				print i.key

test= Database("Pay the ghost")
print test.test()

**Comment by AnthonyBloomer** [comment]
I know what the issue is. I was creating two instances of the self.data array. That's why we can't find they keys! 

The videos method should be like this:

```
 def videos(self, id, page=1):
        videos = []
        result = self._call('movie/' + str(id) + '/videos', 'page=' + str(page))
        [videos.append(obj(**res)) for res in result['results']]
        return videos
```

Then in your test.py

```
videos = tmdb.videos(movieid)
for trailer in videos:
    print trailer.key
```

Hopefully that solves the issue for you!

**Comment by Bobsilvio** [comment]
yes! this work thanks :)
