### ISSUE TITLE
multisearch

### ISSUE THREAD

**Issue by mibj** [AnthonyBloomer/tmdbv3api#105]
Hi , I'm sorry this is not an issue but I don't know how to ask 
How to search with a single request movies and tv ?
Sometimes I don't know if the show is a movie or a serie so I have to try with movie.search() and tv.search() and catch exception
Does exist a method for this ?
-> https://developers.themoviedb.org/3/search/multi-search

Thank you

**Comment by BackrndSource** [comment]
When performing the search you will receive a list with the different objects (tv, movies, people). Within these objects you will find different attributes that are not found in the others. For example in tv you will find "first_release_date" which is not in the others. Or in people "known_for"... Maybe this will help you, if not, look at the response yourself and you may find a better method.
