### ISSUE TITLE
Find class not distributed

### ISSUE THREAD

**Issue by pat218** [AnthonyBloomer/tmdbv3api#107]
Seems I can't import Class Find() when using API.
Looking at the install dir of the lib (pip install) confirms file is missing.
Deleting and installing again (pip uninstall/install) doesn't change anything.
Regards.

**Comment by jlw4049** [comment]
I am unable to import Find() as well

**Comment by AnthonyBloomer** [comment]
Published a new version to PyPi which includes the Find class: https://pypi.org/project/tmdbv3api/1.7.7/
