### ISSUE TITLE
Group don't exist in v1.7.7

### ISSUE THREAD

**Issue by Impre-visible** [AnthonyBloomer/tmdbv3api#114]
Hi, I wanted to import Group, but when I imported, I got an error who said, Group doesn't exist, so I checked the files, and there's no Group.py file, so I guess it's no pushed, cause I uninstalled and reinstalled. Same error.

**Comment by Impre-visible** [comment]
I had to patch my code, but I can make the script work, but, the actual version has not been published to pypi

**Comment by AnthonyBloomer** [comment]
[1.9.0](https://pypi.org/project/tmdbv3api/) is now available on PyPi.
