### ISSUE TITLE
Add __repr__ for objects

### ISSUE THREAD

**Issue by dufferzafar** [AnthonyBloomer/tmdbv3api#14]
Which allows the output to look a bit nicer than it currently does:

```python
>>> from tmdbv3api import Movie 
>>> M = Movie()
>>> M.search("Hello")
[<tmdbv3api.as_obj.AsObj object at 0x7fc3fd7da3c8>, <tmdbv3api.as_obj.AsObj object at 0x7fc3fd7da748>, <tmdbv3api.as_obj.AsObj object at 0x7fc3fd7da4a8>, <tmdbv3api.as_obj.AsObj object at 0x7fc3fd7dacf8>
```

**Comment by AnthonyBloomer** [comment]
Hi @dufferzafar, great suggestion. I'll have a look into adding this.

**Comment by dufferzafar** [comment]
Some context: I needed a TMDB API. Found two of those, this one and [tmdbsimple](https://github.com/celiao/tmdbsimple/)

I started first with yours, because it seemed to be recently updated etc. But as soon as I saw there are no `__repr__` I switched to tmdbsimple. :upside_down_face: 

A comparison amongs the two would be nice.
