### ISSUE TITLE
append_to_response Error on Company.details/Person.details

### ISSUE THREAD

**Issue by romancsandleriksen** [AnthonyBloomer/tmdbv3api#15]
Fixable with 
def _call(self, action, append_to_response=''):
instead of
def _call(self, action, append_to_response):

**Comment by AnthonyBloomer** [comment]
Hi @romancsandleriksen ,

Thanks for raising this issue. I made some changes which caused this. I'll fix it asap.

The version released in PyPi isn't affected. 

Best,
Anthony

**Comment by AnthonyBloomer** [comment]
>reopen until fix is pushed.

**Comment by AnthonyBloomer** [comment]
Fixed with latest release 1.1.0.
