### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by gkovacsp** [AnthonyBloomer/tmdbv3api#17]
Is there a way to select language for the returned information?

The API allows it: https://developers.themoviedb.org/3/getting-started/languages

**Comment by gkovacsp** [comment]
OK, I should have searched before opening the issue, maybe the documentation needs an update.

**Comment by AnthonyBloomer** [comment]
Hi @gkovacsp, Thanks for raising this. I will update the documentation to show how the language can be set.
