### ISSUE TITLE
language parameter not works

### ISSUE THREAD

**Issue by doby** [AnthonyBloomer/tmdbv3api#19]
If I define the language in a python script 
```
tmdb = TMDb()
tmdb.api_key = 'XXXXXX'
tmdb.language = 'fr'
tmdb.debug = True
```

Return is english 

if I modify tmdb.py with 
`
   def __init__(self, debug=False, language='fr', wait_on_rate_limit=True):
`
Result is french .

**Comment by backit** [comment]
if you call:
tmdb = TMDb(language='fr')
it works, this is because the setter does not check if the TMDB_LANGUAGE is already set or not, also calling Movie() overwrite language setting

Why is this closed? The bug is still there!!
