### ISSUE TITLE
Find By External ID

### ISSUE THREAD

**Issue by chrisgtech** [AnthonyBloomer/tmdbv3api#20]
In the API documentation there is a [find by ID](https://developers.themoviedb.org/3/find/find-by-id) method listed, which is useful for looking up movies via something like the IMDB ID. As far as I can tell though this isn't supported in tmdbv3api. Is there a way to call this part of the API or if not can support be added for it?

**Comment by AnthonyBloomer** [comment]
Hi @chrisgtech, thanks for bringing this issue to my attention. I added support for this method in [v1.3.1](https://pypi.org/project/tmdbv3api/)

You can use the API like this:

```python
movie = Movie()
res = movie.external(external_id="tt8155288", external_source="imdb_id")
print(res)
...
```

**Comment by Dr0bac** [comment]
> Hi @chrisgtech, thanks for bringing this issue to my attention. I added support for this method in [v1.3.1](https://pypi.org/project/tmdbv3api/)
> 
> You can use the API like this:
> 
> ```python
> movie = Movie()
> res = movie.external(external_id="tt8155288", external_source="imdb_id")
> print(res)
> ...
> ```

Sorry, does this method support printing movie "id, title, overview, etc..." with simple print(res.id), print(res.title)?
I tried, but i got error:
`'dict' object has no attribute 'id'`
