### ISSUE TITLE
setting language does not work

### ISSUE THREAD

**Issue by backit** [AnthonyBloomer/tmdbv3api#22]
as dolby issue said and i commented (but i cannot reopen),
if you call tmdb=TMDb(language='it')
then language is italian, otherwise it is overwritten by the setter that does not check if TMDB_LANGUAGE exists and has value.
Also calling Movie() overwrite language

Best regards

**Comment by AnthonyBloomer** [comment]
Hey @backit, thank you for bringing this issue to my attention. v1.3.2 has now been released on PyPi which addresses this.

**Comment by backit** [comment]
great solved!!
works on both python 2 and 3
