### ISSUE TITLE
Episode Endpoint does not exist.

### ISSUE THREAD

**Issue by samlovescoding** [AnthonyBloomer/tmdbv3api#29]
Please add an episode endpoint for a TV Series. I have written the base code. Please add to episode.py

File can be found at : https://github.com/samlovescoding/tmdbv3api-unofficial/blob/master/objs/episode.py

Code:
`from tmdbv3api.tmdb import TMDb
from tmdbv3api.as_obj import AsObj

try:
	from urllib import quote
except ImportError:
	from urllib.parse import quote

class Episode(TMDb):

	_urls = {
		'details': '/tv/%s/season/%s/episode/%s/',
	}

	def details(self, tv_id, season_num, episode_num, append_to_response="append_to_response=trailers,images,casts,translations"):
		return AsObj(**self._call(self._urls['details'] % (str(tv_id), str(season_num), str(episode_num)), append_to_response))`

**Comment by AnthonyBloomer** [comment]
Awesome, thank you!
