### ISSUE TITLE
'TV' object has no attribute 'reviews' and keywords

### ISSUE THREAD

**Issue by ylemouel** [AnthonyBloomer/tmdbv3api#40]
Dear support,

I'm trying to get series reviews and keywords, it looks like that it's possible for TV. 

It works well for movies, is it implemented for series in the future?

Thanks

**Comment by AnthonyBloomer** [comment]
@ylemouel, thank you for creating this issue. I've added keywords and reviews methods to the TV class.

**Comment by AnthonyBloomer** [comment]
These TV methods has been added to v1.5.1 and is now available on PyPI: 

https://pypi.org/project/tmdbv3api/

**Comment by ylemouel** [comment]
Thanks a lot, nevertheless I didn't see attributes for cast and crew from get credits (TV).
