### ISSUE TITLE
Missing meta informations in Discover call

### ISSUE THREAD

**Issue by farzeni** [AnthonyBloomer/tmdbv3api#41]
Hello,

First, thank you for sharing this library, I'm really appreciating it.

I was wondering why you are removing meta information about queries in calls which return a list of entities. I'm referring now to Discover API call, where you are calling _self.\_get_obj_ method which transforms the response in a plain python array removing information like, total_pages, total_results and page.

Is there any good reason why you are moving away from official tmdb api spec?

Thanks again for your work and your support

**Comment by AnthonyBloomer** [comment]
Hello @farzeni, good question! When building this, I added the `AsObj` class which allows users to access the TMDb response attributes using a dot notation like so:

``` python
popular = movie.popular()

for p in popular:
    print(p.title)
    print(p.overview)
```

By default, the `get_obj` method will access the `results` array in the TMDb JSON object and transform the response meaning that any metadata outside of the `results` array won't be included in that response. 

However, you can still access the total pages, total results and current page by calling the respective methods in the TMDb class, for example:

``` python
from tmdbv3api import TMDb, Movie

tmdb = TMDb()

movie = Movie()
popular = movie.popular()

print(tmdb.total_results)
print(tmdb.total_pages)
print(tmdb.page)

```

I did look into [Marshmallow](https://marshmallow.readthedocs.io/) whic provides a way nicer mechanism to handle this. Perhaps I'll revisit this at some stage.

 Please let me know if you have any follow up questions in regards to this.

**Comment by farzeni** [comment]
Hi Antony,

Thanks for the hint.  I'm good with your response, feel free to close the issue.
