### ISSUE TITLE
movie.details() returning duplicate subkey "entries" that contains all data again

### ISSUE THREAD

**Issue by jasonsokolowski** [AnthonyBloomer/tmdbv3api#43]
Result set from movie.details() duplicates all data again inside "entries". Forced to pop from the dictionary needlessly. 

movie_details = movie.details(movie_id).__dict__.pop("entries",None)

Also possible to allow us to select what to include in details? The details API doesn't include things like cast,crew, etc. 

![alien](https://user-images.githubusercontent.com/21149998/81505572-3c388500-92be-11ea-9610-df2ec5d82d9b.png)

**Comment by AnthonyBloomer** [comment]
Hello @jasonsokolowski,

Good find. Thanks for creating this issue. 

The reason for this issue is because when the `AsObj` class is being instantiated, I set:

``` python
self.entries = entries
```

The reason for this is wanted to make it available to the `__repr__` method so I can return the name of the movie or tv show as the object name. The problem here is that every time `AsObj` gets called, an entries dictionary is created and is available globally.  What I've done is made that entries variable private so it's not accessible from outside the `AsObj` class. 

In regard to your second question, by default, the `details` method does append cast data to the response. You can change this behaviour by setting the `append_to_response` parameter:

``` python
m = movie.details(111, append_to_response="casts,videos")
```

You can then access that data like so:

```
print(m.videos['results'][0]['id'])
print(m.casts['cast'][0]['character'])
```

**Comment by jasonsokolowski** [comment]
@AnthonyBloomer Thanks for the prompt response and resolution! Looking at the code below, it appears that details appends videos,trailers,images,casts,translations,keywords by default. If you call movie details straight from their API, that information is omitted. Thanks!

def details(self, movie_id, append_to_response='videos,trailers,images,casts,translations,keywords'):

https://github.com/AnthonyBloomer/tmdbv3api/blob/4aebfa59a67cab14e9b4c06bd5fb0176b581a81c/tmdbv3api/objs/movie.py#L39

**Comment by jasonsokolowski** [comment]
@AnthonyBloomer Possible to push this to a new release? Thanks!

**Comment by AnthonyBloomer** [comment]
@jasonsokolowski 1.6.0 has just been published to PyPy: https://pypi.org/project/tmdbv3api/1.6.0/

**Comment by jasonsokolowski** [comment]
> @jasonsokolowski 1.6.0 has just been published to PyPy: https://pypi.org/project/tmdbv3api/1.6.0/

Thanks for this, unfortunately looks like entries is back, but now prepended with_AsObj__, see attached.

![Screenshot from 2020-05-25 10-07-39](https://user-images.githubusercontent.com/21149998/82820172-b432ad80-9e6f-11ea-99a1-e190811282ad.png)

**Comment by AnthonyBloomer** [comment]
What tool are you using to see the object attributes?

**Comment by jasonsokolowski** [comment]
> What tool are you using to see the object attributes?

This is just the raw json I'm pasting into https://codebeautify.org/jsonviewer for easier viewing, copied from database or print output is the same. 

{"id": 371645, "adult": false, "casts": {"cast": [{"id": 4783, "name": "Sam Neill", "order": 0, "gender": 2, "cast_id": 2, "character": "Hec Faulkner", "credit_id": "56663ec7c3a368069f001828", "profile_path": "/lTKvnzwdKrgH7ZYlslFvNQfSeFs.jpg"}, {"id": 1139349, "name": "Julian Dennison", "order": 1, "gender": 2, "cast_id": 4, "character": "Ricky Baker", "credit_id": "56663efb92514179e10019fe", "profile_path": "/9wmT8RDfJL2yKuY5AeJuDTkHSJe.jpg"}, {"id": 1288797, "name": "Rima Te Wiata", "order": 2, "gender": 1, "cast_id": 3, "character": "Bella M. Faulkner", "credit_id": "56663ee39251411ca10012d7", "profile_path": "/8a2q62pvqwvIb0D86nFPI0p6ebW.jpg"}, {"id": 15298, "name": "Rachel House", "order": 3, "gender": 1, "cast_id": 5, "character": "Paula Hall", "credit_id": "56ad1c92c3a3681c47006fa0", "profile_path": "/mAQMUI507TmET25aF8tQIxQNCT8.jpg"}, {"id": 82666, "name": "Rhys Darby", "order": 4, "gender": 2, "cast_id": 7, "character": "Psycho Sam", "credit_id": "56ad1c93c3a3681c34006499", "profile_path": "/q6Grd42OgTUbRcTarZhR9piA6a5.jpg"}, {"id": 89843, "name": "Oscar Kightley", "order": 5, "gender": 2, "cast_id": 6, "character": "Officer Andy", "credit_id": "56ad1c92c3a3681c31006bd9", "profile_path": "/rTklFzrvcwMJJANfFmP2LZuDjD6.jpg"}, {"id": 1622074, "name": "Tioreore Ngatai-Melbourne", "order": 6, "gender": 0, "cast_id": 17, "character": "Kahu", "credit_id": "573cde9dc3a3687dc00009a7", "profile_path": null}, {"id": 1153006, "name": "Troy Kingi", "order": 7, "gender": 0, "cast_id": 18, "character": "TK", "credit_id": "573cde9dc3a368446c0004f7", "profile_path": null}, {"id": 939388, "name": "Cohen Holloway", "order": 8, "gender": 2, "cast_id": 8, "character": "Hugh", "credit_id": "56ad1c939251417e1a006777", "profile_path": "/7qWqBZk4arFgx7TJpi7uXe6eH2z.jpg"}, {"id": 1153004, "name": "Stan Walker", "order": 9, "gender": 0, "cast_id": 10, "character": "Ron", "credit_id": "56ad1c94c3a3681c3700638f", "profile_path": null}, {"id": 1334712, "name": "Mike Minogue", "order": 10, "gender": 2, "cast_id": 9, "character": "Joe", "credit_id": "56ad1c93c3a3681c3400649b", "profile_path": "/tZoCqJgcXotaqADXeZIJkeLeY54.jpg"}, {"id": 1570328, "name": "Hamish Parkinson", "order": 11, "gender": 0, "cast_id": 11, "character": "Gavin", "credit_id": "56ad1c949251417e1a00677a", "profile_path": "/2nBXQDn5nFkrLHS4hwtH2WLUGkc.jpg"}, {"id": 55934, "name": "Taika Waititi", "order": 12, "gender": 2, "cast_id": 19, "character": "Minister", "credit_id": "573cde9e92514174260004d9", "profile_path": "/bqecNGun4FHvKqXga6D9V51DTBN.jpg"}, {"id": 1570329, "name": "Lloyd Scott", "order": 14, "gender": 0, "cast_id": 13, "character": "Tourist", "credit_id": "56ad1c95c3a3681c3b006ee2", "profile_path": "/uJ1TfWAai9uhOGfndDGxHa2bnpG.jpg"}, {"id": 1622075, "name": "Selena Wolfe", "order": 15, "gender": 0, "cast_id": 20, "character": "Organ Player", "credit_id": "573cde9ec3a3687db6000b4b", "profile_path": null}, {"id": 1622076, "name": "Mabelle Dennison", "order": 16, "gender": 0, "cast_id": 21, "character": "Church Lady", "credit_id": "573cde9e9251413f650009c0", "profile_path": null}, {"id": 1622077, "name": "Sonia Spyve", "order": 17, "gender": 1, "cast_id": 22, "character": "Court Lawyer", "credit_id": "573cde9fc3a3684436000521", "profile_path": "/59EzrWK5avpUIwjJNehz2dkgO5P.jpg"}, {"id": 1622078, "name": "Timothy Herbert", "order": 18, "gender": 2, "cast_id": 23, "character": "Court Lawyer", "credit_id": "573cde9fc3a3687db6000b50", "profile_path": null}, {"id": 1671691, "name": "Stu Giles", "order": 19, "gender": 0, "cast_id": 28, "character": "Sick Man", "credit_id": "57c35144925141537f000b9f", "profile_path": null}, {"id": 1671692, "name": "Selina Woulfe", "order": 20, "gender": 0, "cast_id": 29, "character": "Organ Player", "credit_id": "57c3514592514128610015cd", "profile_path": null}, {"id": 1671693, "name": "Tuss", "order": 21, "gender": 0, "cast_id": 30, "character": "Tupac", "credit_id": "57c35145c3a3683274000b4b", "profile_path": null}, {"id": 1671694, "name": "Finn", "order": 22, "gender": 0, "cast_id": 31, "character": "Zag", "credit_id": "57c3514592514128610015d3", "profile_path": null}], "crew": [{"id": 55934, "job": "Screenplay", "name": "Taika Waititi", "gender": 2, "credit_id": "56663ea2c3a36806a2001994", "department": "Writing", "profile_path": "/bqecNGun4FHvKqXga6D9V51DTBN.jpg"}, {"id": 55934, "job": "Director", "name": "Taika Waititi", "gender": 2, "credit_id": "56663e92c3a36806a80018aa", "department": "Directing", "profile_path": "/bqecNGun4FHvKqXga6D9V51DTBN.jpg"}, {"id": 55934, "job": "Producer", "name": "Taika Waititi", "gender": 2, "credit_id": "580c40ebc3a368258f009240", "department": "Production", "profile_path": "/bqecNGun4FHvKqXga6D9V51DTBN.jpg"}, {"id": 76847, "job": "Production Design", "name": "Neville Stevenson", "gender": 0, "credit_id": "57d91fc2c3a3685342004cfb", "department": "Art", "profile_path": null}, {"id": 1037893, "job": "Stunt Driver", "name": "Glen Levy", "gender": 2, "credit_id": "5bdcdfa492514137d8000c3a", "department": "Crew", "profile_path": "/dUhVp0mxloOoKWmnvIPgAy3kz5Y.jpg"}, {"id": 1122452, "job": "Director of Photography", "name": "Lachlan Milne", "gender": 2, "credit_id": "57d91f16c3a36878e9006126", "department": "Camera", "profile_path": null}, {"id": 1150130, "job": "Producer", "name": "Leanne Saunders", "gender": 1, "credit_id": "57d91f32925141682a004c67", "department": "Production", "profile_path": null}, {"id": 1193051, "job": "Producer", "name": "Matt Noonan", "gender": 0, "credit_id": "57d91f2592514168de00494b", "department": "Production", "profile_path": null}, {"id": 1310062, "job": "Executive Producer", "name": "Charlie McClellan", "gender": 0, "credit_id": "57d91f4fc3a36878e900613b", "department": "Production", "profile_path": null}, {"id": 1404683, "job": "Editor", "name": "Yana Gorskaya", "gender": 0, "credit_id": "57d91f9bc3a36852f4005078", "department": "Editing", "profile_path": null}, {"id": 1409489, "job": "Editor", "name": "Tom Eagles", "gender": 0, "credit_id": "57d91f8ec3a36854930051d1", "department": "Editing", "profile_path": null}, {"id": 1501949, "job": "Editor", "name": "Luke Haigh", "gender": 0, "credit_id": "57d91fa892514168de004977", "department": "Editing", "profile_path": null}, {"id": 1535692, "job": "Line Producer", "name": "Sarah Cook", "gender": 0, "credit_id": "57d91f5fc3a36854930051c7", "department": "Production", "profile_path": null}, {"id": 1550516, "job": "Producer", "name": "Carthew Neal", "gender": 0, "credit_id": "571237c49251413031000596", "department": "Production", "profile_path": null}, {"id": 1583552, "job": "Casting", "name": "Stu Turner", "gender": 2, "credit_id": "57d91fb5c3a3685383004d33", "department": "Production", "profile_path": "/hkCqFcmSV2f6ueJdhYmbdNbKAK9.jpg"}, {"id": 1605314, "job": "Book", "name": "Barry Crump", "gender": 0, "credit_id": "570e9e6192514102ad000443", "department": "Writing", "profile_path": null}, {"id": 1671688, "job": "Original Music Composer", "name": "Lukasz Pawel Buda", "gender": 0, "credit_id": "57c350d5c3a368321d000d82", "department": "Sound", "profile_path": null}, {"id": 1671689, "job": "Original Music Composer", "name": "Samuel Scott", "gender": 0, "credit_id": "57c350e99251413c3400114d", "department": "Sound", "profile_path": null}, {"id": 1671690, "job": "Original Music Composer", "name": "Conrad Wedde", "gender": 0, "credit_id": "57c350f392514136660011dd", "department": "Sound", "profile_path": null}, {"id": 1678888, "job": "Art Direction", "name": "Jon Lithgow", "gender": 0, "credit_id": "57d91fcd9251416851004a95", "department": "Art", "profile_path": null}, {"id": 1678889, "job": "Costume Design", "name": "Kristin Seth", "gender": 0, "credit_id": "57d91fdac3a3685342004d09", "department": "Costume & Make-Up", "profile_path": null}, {"id": 1678890, "job": "Makeup Artist", "name": "Jacinta Driver", "gender": 0, "credit_id": "57d91fe89251415a6c004f7e", "department": "Costume & Make-Up", "profile_path": null}, {"id": 1938083, "job": "Executive Producer", "name": "James Wallace", "gender": 0, "credit_id": "5a2c6783c3a3680b8d140747", "department": "Production", "profile_path": null}]}, "title": "Hunt for the Wilderpeople", "video": false, "budget": 2500000, "genres": [{"id": 12, "name": "Adventure"}, {"id": 35, "name": "Comedy"}, {"id": 18, "name": "Drama"}], "images": {"posters": [{"width": 1400, "height": 2000, "file_path": "/xQZJ4vVojBKihoNlfx2wCVnQqop.jpg", "iso_639_1": "en", "vote_count": 1, "aspect_ratio": 0.7, "vote_average": 5.312}, {"width": 1000, "height": 1500, "file_path": "/skQqcMa1nSt7aqRRJiSy44KGSC1.jpg", "iso_639_1": "en", "vote_count": 0, "aspect_ratio": 0.6666666666666666, "vote_average": 0.0}, {"width": 1000, "height": 1500, "file_path": "/sIc4uv8RjvjKkPFNUFt7O5DjGfv.jpg", "iso_639_1": "en", "vote_count": 0, "aspect_ratio": 0.6666666666666666, "vote_average": 0.0}, {"width": 1000, "height": 1500, "file_path": "/aC5hkJvP3jWj9Fp6XxubCuUZivE.jpg", "iso_639_1": "en", "vote_count": 0, "aspect_ratio": 0.6666666666666666, "vote_average": 0.0}, {"width": 1000, "height": 1500, "file_path": "/rg2IXW5CBV0DdAmDvMo5TXwpnjd.jpg", "iso_639_1": "en", "vote_count": 0, "aspect_ratio": 0.6666666666666666, "vote_average": 0.0}, {"width": 1000, "height": 1500, "file_path": "/xQuZ1hUf5rMxhJXvBL00cMFOnpa.jpg", "iso_639_1": "en", "vote_count": 0, "aspect_ratio": 0.6666666666666666, "vote_average": 0.0}], "backdrops": [{"width": 1920, "height": 1080, "file_path": "/l5WpKOCwQLV0EWmGmtRCBRelXce.jpg", "iso_639_1": "en", "vote_count": 0, "aspect_ratio": 1.777777777777778, "vote_average": 0.0}]}, "status": "Released", "videos": {"results": [{"id": "5add0fbe925141041b000bea", "key": "dPaU4Gymt3E", "name": "Hunt for the Wilderpeople Official Trailer 1 (2016) - Sam Neill, Rhys Darby Movie HD", "site": "YouTube", "size": 1080, "type": "Trailer", "iso_639_1": "en", "iso_3166_1": "US"}]}, "imdb_id": "tt4698684", "revenue": 23200000, "runtime": 101, "tagline": "Nature just got gangster", "homepage": "http://wilderpeople.film", "overview": "Ricky is a defiant young city kid who finds himself on the run with his cantankerous foster uncle in the wild New Zealand bush. A national manhunt ensues, and the two are forced to put aside their differences and work together to survive.", "trailers": {"youtube": [{"name": "Hunt for the Wilderpeople Official Trailer 1 (2016) - Sam Neill, Rhys Darby Movie HD", "size": "HD", "type": "Trailer", "source": "dPaU4Gymt3E"}], "quicktime": []}, "popularity": 12.425, "vote_count": 1153, "poster_path": "/xQZJ4vVojBKihoNlfx2wCVnQqop.jpg", "release_date": "2016-03-31", "vote_average": 7.8, "backdrop_path": "/5paubD86aMug7nUbn3NkMzSBDaD.jpg", "original_title": "Hunt for the Wilderpeople", "_AsObj__entries": {"id": 371645, "adult": false, "casts": {"cast": [{"id": 4783, "name": "Sam Neill", "order": 0, "gender": 2, "cast_id": 2, "character": "Hec Faulkner", "credit_id": "56663ec7c3a368069f001828", "profile_path": "/lTKvnzwdKrgH7ZYlslFvNQfSeFs.jpg"}, {"id": 1139349, "name": "Julian Dennison", "order": 1, "gender": 2, "cast_id": 4, "character": "Ricky Baker", "credit_id": "56663efb92514179e10019fe", "profile_path": "/9wmT8RDfJL2yKuY5AeJuDTkHSJe.jpg"}, {"id": 1288797, "name": "Rima Te Wiata", "order": 2, "gender": 1, "cast_id": 3, "character": "Bella M. Faulkner", "credit_id": "56663ee39251411ca10012d7", "profile_path": "/8a2q62pvqwvIb0D86nFPI0p6ebW.jpg"}, {"id": 15298, "name": "Rachel House", "order": 3, "gender": 1, "cast_id": 5, "character": "Paula Hall", "credit_id": "56ad1c92c3a3681c47006fa0", "profile_path": "/mAQMUI507TmET25aF8tQIxQNCT8.jpg"}, {"id": 82666, "name": "Rhys Darby", "order": 4, "gender": 2, "cast_id": 7, "character": "Psycho Sam", "credit_id": "56ad1c93c3a3681c34006499", "profile_path": "/q6Grd42OgTUbRcTarZhR9piA6a5.jpg"}, {"id": 89843, "name": "Oscar Kightley", "order": 5, "gender": 2, "cast_id": 6, "character": "Officer Andy", "credit_id": "56ad1c92c3a3681c31006bd9", "profile_path": "/rTklFzrvcwMJJANfFmP2LZuDjD6.jpg"}, {"id": 1622074, "name": "Tioreore Ngatai-Melbourne", "order": 6, "gender": 0, "cast_id": 17, "character": "Kahu", "credit_id": "573cde9dc3a3687dc00009a7", "profile_path": null}, {"id": 1153006, "name": "Troy Kingi", "order": 7, "gender": 0, "cast_id": 18, "character": "TK", "credit_id": "573cde9dc3a368446c0004f7", "profile_path": null}, {"id": 939388, "name": "Cohen Holloway", "order": 8, "gender": 2, "cast_id": 8, "character": "Hugh", "credit_id": "56ad1c939251417e1a006777", "profile_path": "/7qWqBZk4arFgx7TJpi7uXe6eH2z.jpg"}, {"id": 1153004, "name": "Stan Walker", "order": 9, "gender": 0, "cast_id": 10, "character": "Ron", "credit_id": "56ad1c94c3a3681c3700638f", "profile_path": null}, {"id": 1334712, "name": "Mike Minogue", "order": 10, "gender": 2, "cast_id": 9, "character": "Joe", "credit_id": "56ad1c93c3a3681c3400649b", "profile_path": "/tZoCqJgcXotaqADXeZIJkeLeY54.jpg"}, {"id": 1570328, "name": "Hamish Parkinson", "order": 11, "gender": 0, "cast_id": 11, "character": "Gavin", "credit_id": "56ad1c949251417e1a00677a", "profile_path": "/2nBXQDn5nFkrLHS4hwtH2WLUGkc.jpg"}, {"id": 55934, "name": "Taika Waititi", "order": 12, "gender": 2, "cast_id": 19, "character": "Minister", "credit_id": "573cde9e92514174260004d9", "profile_path": "/bqecNGun4FHvKqXga6D9V51DTBN.jpg"}, {"id": 1570329, "name": "Lloyd Scott", "order": 14, "gender": 0, "cast_id": 13, "character": "Tourist", "credit_id": "56ad1c95c3a3681c3b006ee2", "profile_path": "/uJ1TfWAai9uhOGfndDGxHa2bnpG.jpg"}, {"id": 1622075, "name": "Selena Wolfe", "order": 15, "gender": 0, "cast_id": 20, "character": "Organ Player", "credit_id": "573cde9ec3a3687db6000b4b", "profile_path": null}, {"id": 1622076, "name": "Mabelle Dennison", "order": 16, "gender": 0, "cast_id": 21, "character": "Church Lady", "credit_id": "573cde9e9251413f650009c0", "profile_path": null}, {"id": 1622077, "name": "Sonia Spyve", "order": 17, "gender": 1, "cast_id": 22, "character": "Court Lawyer", "credit_id": "573cde9fc3a3684436000521", "profile_path": "/59EzrWK5avpUIwjJNehz2dkgO5P.jpg"}, {"id": 1622078, "name": "Timothy Herbert", "order": 18, "gender": 2, "cast_id": 23, "character": "Court Lawyer", "credit_id": "573cde9fc3a3687db6000b50", "profile_path": null}, {"id": 1671691, "name": "Stu Giles", "order": 19, "gender": 0, "cast_id": 28, "character": "Sick Man", "credit_id": "57c35144925141537f000b9f", "profile_path": null}, {"id": 1671692, "name": "Selina Woulfe", "order": 20, "gender": 0, "cast_id": 29, "character": "Organ Player", "credit_id": "57c3514592514128610015cd", "profile_path": null}, {"id": 1671693, "name": "Tuss", "order": 21, "gender": 0, "cast_id": 30, "character": "Tupac", "credit_id": "57c35145c3a3683274000b4b", "profile_path": null}, {"id": 1671694, "name": "Finn", "order": 22, "gender": 0, "cast_id": 31, "character": "Zag", "credit_id": "57c3514592514128610015d3", "profile_path": null}], "crew": [{"id": 55934, "job": "Screenplay", "name": "Taika Waititi", "gender": 2, "credit_id": "56663ea2c3a36806a2001994", "department": "Writing", "profile_path": "/bqecNGun4FHvKqXga6D9V51DTBN.jpg"}, {"id": 55934, "job": "Director", "name": "Taika Waititi", "gender": 2, "credit_id": "56663e92c3a36806a80018aa", "department": "Directing", "profile_path": "/bqecNGun4FHvKqXga6D9V51DTBN.jpg"}, {"id": 55934, "job": "Producer", "name": "Taika Waititi", "gender": 2, "credit_id": "580c40ebc3a368258f009240", "department": "Production", "profile_path": "/bqecNGun4FHvKqXga6D9V51DTBN.jpg"}, {"id": 76847, "job": "Production Design", "name": "Neville Stevenson", "gender": 0, "credit_id": "57d91fc2c3a3685342004cfb", "department": "Art", "profile_path": null}, {"id": 1037893, "job": "Stunt Driver", "name": "Glen Levy", "gender": 2, "credit_id": "5bdcdfa492514137d8000c3a", "department": "Crew", "profile_path": "/dUhVp0mxloOoKWmnvIPgAy3kz5Y.jpg"}, {"id": 1122452, "job": "Director of Photography", "name": "Lachlan Milne", "gender": 2, "credit_id": "57d91f16c3a36878e9006126", "department": "Camera", "profile_path": null}, {"id": 1150130, "job": "Producer", "name": "Leanne Saunders", "gender": 1, "credit_id": "57d91f32925141682a004c67", "department": "Production", "profile_path": null}, {"id": 1193051, "job": "Producer", "name": "Matt Noonan", "gender": 0, "credit_id": "57d91f2592514168de00494b", "department": "Production", "profile_path": null}, {"id": 1310062, "job": "Executive Producer", "name": "Charlie McClellan", "gender": 0, "credit_id": "57d91f4fc3a36878e900613b", "department": "Production", "profile_path": null}, {"id": 1404683, "job": "Editor", "name": "Yana Gorskaya", "gender": 0, "credit_id": "57d91f9bc3a36852f4005078", "department": "Editing", "profile_path": null}, {"id": 1409489, "job": "Editor", "name": "Tom Eagles", "gender": 0, "credit_id": "57d91f8ec3a36854930051d1", "department": "Editing", "profile_path": null}, {"id": 1501949, "job": "Editor", "name": "Luke Haigh", "gender": 0, "credit_id": "57d91fa892514168de004977", "department": "Editing", "profile_path": null}, {"id": 1535692, "job": "Line Producer", "name": "Sarah Cook", "gender": 0, "credit_id": "57d91f5fc3a36854930051c7", "department": "Production", "profile_path": null}, {"id": 1550516, "job": "Producer", "name": "Carthew Neal", "gender": 0, "credit_id": "571237c49251413031000596", "department": "Production", "profile_path": null}, {"id": 1583552, "job": "Casting", "name": "Stu Turner", "gender": 2, "credit_id": "57d91fb5c3a3685383004d33", "department": "Production", "profile_path": "/hkCqFcmSV2f6ueJdhYmbdNbKAK9.jpg"}, {"id": 1605314, "job": "Book", "name": "Barry Crump", "gender": 0, "credit_id": "570e9e6192514102ad000443", "department": "Writing", "profile_path": null}, {"id": 1671688, "job": "Original Music Composer", "name": "Lukasz Pawel Buda", "gender": 0, "credit_id": "57c350d5c3a368321d000d82", "department": "Sound", "profile_path": null}, {"id": 1671689, "job": "Original Music Composer", "name": "Samuel Scott", "gender": 0, "credit_id": "57c350e99251413c3400114d", "department": "Sound", "profile_path": null}, {"id": 1671690, "job": "Original Music Composer", "name": "Conrad Wedde", "gender": 0, "credit_id": "57c350f392514136660011dd", "department": "Sound", "profile_path": null}, {"id": 1678888, "job": "Art Direction", "name": "Jon Lithgow", "gender": 0, "credit_id": "57d91fcd9251416851004a95", "department": "Art", "profile_path": null}, {"id": 1678889, "job": "Costume Design", "name": "Kristin Seth", "gender": 0, "credit_id": "57d91fdac3a3685342004d09", "department": "Costume & Make-Up", "profile_path": null}, {"id": 1678890, "job": "Makeup Artist", "name": "Jacinta Driver", "gender": 0, "credit_id": "57d91fe89251415a6c004f7e", "department": "Costume & Make-Up", "profile_path": null}, {"id": 1938083, "job": "Executive Producer", "name": "James Wallace", "gender": 0, "credit_id": "5a2c6783c3a3680b8d140747", "department": "Production", "profile_path": null}]}, "title": "Hunt for the Wilderpeople", "video": false, "budget": 2500000, "genres": [{"id": 12, "name": "Adventure"}, {"id": 35, "name": "Comedy"}, {"id": 18, "name": "Drama"}], "images": {"posters": [{"width": 1400, "height": 2000, "file_path": "/xQZJ4vVojBKihoNlfx2wCVnQqop.jpg", "iso_639_1": "en", "vote_count": 1, "aspect_ratio": 0.7, "vote_average": 5.312}, {"width": 1000, "height": 1500, "file_path": "/skQqcMa1nSt7aqRRJiSy44KGSC1.jpg", "iso_639_1": "en", "vote_count": 0, "aspect_ratio": 0.6666666666666666, "vote_average": 0.0}, {"width": 1000, "height": 1500, "file_path": "/sIc4uv8RjvjKkPFNUFt7O5DjGfv.jpg", "iso_639_1": "en", "vote_count": 0, "aspect_ratio": 0.6666666666666666, "vote_average": 0.0}, {"width": 1000, "height": 1500, "file_path": "/aC5hkJvP3jWj9Fp6XxubCuUZivE.jpg", "iso_639_1": "en", "vote_count": 0, "aspect_ratio": 0.6666666666666666, "vote_average": 0.0}, {"width": 1000, "height": 1500, "file_path": "/rg2IXW5CBV0DdAmDvMo5TXwpnjd.jpg", "iso_639_1": "en", "vote_count": 0, "aspect_ratio": 0.6666666666666666, "vote_average": 0.0}, {"width": 1000, "height": 1500, "file_path": "/xQuZ1hUf5rMxhJXvBL00cMFOnpa.jpg", "iso_639_1": "en", "vote_count": 0, "aspect_ratio": 0.6666666666666666, "vote_average": 0.0}], "backdrops": [{"width": 1920, "height": 1080, "file_path": "/l5WpKOCwQLV0EWmGmtRCBRelXce.jpg", "iso_639_1": "en", "vote_count": 0, "aspect_ratio": 1.777777777777778, "vote_average": 0.0}]}, "status": "Released", "videos": {"results": [{"id": "5add0fbe925141041b000bea", "key": "dPaU4Gymt3E", "name": "Hunt for the Wilderpeople Official Trailer 1 (2016) - Sam Neill, Rhys Darby Movie HD", "site": "YouTube", "size": 1080, "type": "Trailer", "iso_639_1": "en", "iso_3166_1": "US"}]}, "imdb_id": "tt4698684", "revenue": 23200000, "runtime": 101, "tagline": "Nature just got gangster", "homepage": "http://wilderpeople.film", "overview": "Ricky is a defiant young city kid who finds himself on the run with his cantankerous foster uncle in the wild New Zealand bush. A national manhunt ensues, and the two are forced to put aside their differences and work together to survive.", "trailers": {"youtube": [{"name": "Hunt for the Wilderpeople Official Trailer 1 (2016) - Sam Neill, Rhys Darby Movie HD", "size": "HD", "type": "Trailer", "source": "dPaU4Gymt3E"}], "quicktime": []}, "popularity": 12.425, "vote_count": 1153, "poster_path": "/xQZJ4vVojBKihoNlfx2wCVnQqop.jpg", "release_date": "2016-03-31", "vote_average": 7.8, "backdrop_path": "/5paubD86aMug7nUbn3NkMzSBDaD.jpg", "original_title": "Hunt for the Wilderpeople", "spoken_languages": [{"name": "English", "iso_639_1": "en"}], "original_language": "en", "production_companies": [{"id": 6510, "name": "Defender Films", "logo_path": null, "origin_country": "NZ"}, {"id": 76342, "name": "Piki Films", "logo_path": "/i53Cvs0mWLEhrRaPOpUXj4lJxDJ.png", "origin_country": "NZ"}, {"id": 81364, "name": "Curious Film", "logo_path": null, "origin_country": ""}], "production_countries": [{"name": "New Zealand", "iso_3166_1": "NZ"}], "belongs_to_collection": null}, "spoken_languages": [{"name": "English", "iso_639_1": "en"}], "original_language": "en", "production_companies": [{"id": 6510, "name": "Defender Films", "logo_path": null, "origin_country": "NZ"}, {"id": 76342, "name": "Piki Films", "logo_path": "/i53Cvs0mWLEhrRaPOpUXj4lJxDJ.png", "origin_country": "NZ"}, {"id": 81364, "name": "Curious Film", "logo_path": null, "origin_country": ""}], "production_countries": [{"name": "New Zealand", "iso_3166_1": "NZ"}], "belongs_to_collection": null}

**Comment by jasonsokolowski** [comment]
Also, entirely possible going about this the wrong way. Just need to extract the raw JSON from your movie object, as if it came direct from the API,  so I can import into database. Right now going about the  dict route, and saving in from there.

**Comment by AnthonyBloomer** [comment]
Thanks for providing that extra detail @jasonsokolowski. It's very helpful. So that private variables hack I used previously doesn't work when you do something like:

``` python
print(json.dumps(show[0].__dict__))
```

I could rewrite the AsObj class to something such as:

``` python
class AsObj:
    def __init__(self, **entries):
        if 'name' in entries:
            self.obj_name = entries['name']
        elif 'title' in entries:
            self.obj_name = entries['title']
        else:
            self.obj_name = "TMDb Obj"

        self.__dict__.update(entries)

    def __repr__(self):
        return self.obj_name
```

However, that will result in a duplicate key for the tv show or movie name. Would this workaround be viable? I like the object repr feature so I don't really want to remove that functionality.

**Comment by jasonsokolowski** [comment]
Ideally would like to avoid all duplicates, is it possible to have a method that presents the json encoded string of the data? If not, I can deal with just having the duplicate "entries" as before, but needs to be documented for everyone else's future reference. Ends up duplicating a lot of data for people doing what I'm doing. Dumping API data directly to jsonb field in postgres from Django. 

thanks!

**Comment by AnthonyBloomer** [comment]
Hello @jasonsokolowski,

I've pushed a fix that removes the additional entries dictionary. This fix is not ideal as it does create the additional `obj_name` attribute so the user can get the name of tv or movie via the `__repr__` method. 

I have thought about the JSON encoded response but I'm not sure how I could include this with how the library has been designed. If you do have any ideas of how that could work, please let me know and we can work on getting this included. 

Thanks again for bringing this issue to my attention!

**Comment by miriki** [comment]
Maybe I missed it, but: Is there (now) a way to get the (kind of "raw") json data? Right now I get the "AsObj" type from e.g. Movie().details( imdb, req_append ). I'd like to save the json into a text file. How about a .getJson() method that uses the output from "json = req.json()" in (actually) line 156 of tmdb.py?

**Comment by meisnate12** [comment]
Is there any reason just saving the dict won't work? The JSON raw data would be hard to store in AsObj since you don't always get one AsObj. many calls will instead return you a list of AsObjs.

**Comment by meisnate12** [comment]
Just return str(AsObj) and it will print the json also that's not how you get a movie via IMDb ID

**Comment by miriki** [comment]
@meisnate12 

> str(AsObj) and it will print the json
Ah, then my "Maybe I missed it" has to be answered with a definitive "yes". ;-) Thank you very much!

> to find the movie an IMDb ID will not work
Did you try it? ;-) I was used to the tmdb via a VB.Net program I have written years ago. And I have used the IMDB ID directly in the http request all the time. And: movie.details() happily accepts it, too. And yes, returns the correct information so far. Yet I didn't stumble across any side effects.

But thanks again for the Str() hint!

**Comment by meisnate12** [comment]
no problem and yea apparently that does work but only for movies. It's just not documented in their API docs but thats good to know!
