### ISSUE TITLE
Standardize external_ids() between TV and Movie

### ISSUE THREAD

**Issue by Archmonger** [AnthonyBloomer/tmdbv3api#46]
Currently `Movie.external_ids()` returns a `dict`, while `TV.external_ids()` returns a `TMDB Obj` (`AsObj`).

Having the two return different return types for the same function name is inconsistent. I personally recommend changing TV to return a `dict`.

**Comment by AnthonyBloomer** [comment]
Hello @Archmonger, thank you for creating this issue! I've updated the `external_ids` method to return a dict and published [v1.6.2](https://pypi.org/project/tmdbv3api/1.6.2/) to PyPi. You can install the latest version using pip:

```
pip install tmdbv3api==1.6.2
```
