### ISSUE TITLE
Is it possible to search for a movie by name and year?

### ISSUE THREAD

**Issue by FlexMcMurphy** [AnthonyBloomer/tmdbv3api#49]
Hello,

I am using:
tmdbv3api-1.6.2-py2.py3-none-any.whl

```
from tmdbv3api import Movie
movie = Movie()
search = movie.search('Mad Max')
for res in search:
    print(res.id)
    print(res.title)

```

Is there a method that lets you search by movie name and year also?

Something like..
`search = movie.search('Mad Max (1979)')`

Actually is there documentation about all the methods available in tmdbv3api? Or is that all of them [on this page](https://pypi.org/project/tmdbv3api/)?

Cheers,
Flex

**Comment by BackrndSource** [comment]
Soon it will be possible once the pull request #51 is accepted.
You can do it like this:

```
from tmdbv3api import Search
search = Search()
results = search.movies({"query": "Mad Max", "year": 1979})
for result in results:
     print(result.title)
     print(result.release_date)
```

**Comment by meisnate12** [comment]
There are [examples](https://github.com/AnthonyBloomer/tmdbv3api/tree/master/examples) that might be able to help

you can also look at the [files](https://github.com/AnthonyBloomer/tmdbv3api/tree/master/tmdbv3api/objs) to see exactly what methods they have

Then to see what values those method responses have look at the [TMDb API](https://developers.themoviedb.org/3/getting-started/introduction)

For example [movies.py](https://github.com/AnthonyBloomer/tmdbv3api/blob/master/tmdbv3api/objs/movie.py) has the `details` method which calls the api using the url defined under `_urls` that looks like `"details": "/movie/%s",` looking at the [API's Movie Section - Get Details](https://developers.themoviedb.org/3/movies/get-movie-details) you can tell that its called using `GET /movie/{movie_id}` which equates to the url tmdbv3api used so thats how you know your call using tmdbv3api hit the right endpoint your looking at. Also on that page you can see all the keys that are accessible be the object after the call.

**Comment by jay-ramani** [comment]
I tried the example code (snippet copied below as well) at https://github.com/AnthonyBloomer/tmdbv3api/commit/0b68f75fa17f1cd475f0883596fcc7f286bb8270#diff-3843809f6f44e13a0a6a318c745b1eaf01251ab578a6dcb678c67563814cb87e verbatim (except supplying my own TMDB API key), and it throws an exception.

```python
from tmdbv3api import TMDb, Search

tmdb = TMDb()
tmdb.api_key="use your own TMDB API key"

search = Search()

results = search.movies({"query": "Matrix", "year": 1999})

for result in results:
    print(result.title)
    print(result.overview)
```

```
    results = search.movies({"query": "Matrix", "year": 1999})
  File "C:\Program Files\Python\Lib\site-packages\tmdbv3api\objs\search.py", line 70, in movies
    params = "query=%s&page=%s" % (quote(term), page)
                                   ~~~~~^^^^^^
  File "C:\Program Files\Python\Lib\urllib\parse.py", line 927, in quote
    return quote_from_bytes(string, safe)
  File "C:\Program Files\Python\Lib\urllib\parse.py", line 957, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
```

```
python --version
Python 3.13.3
```
@AnthonyBloomer, @BackrndSource, was this tested before merging the code? If not, could you fix the example code?

Not sure if this is because UTF-8 is enabled on Windows OS (24H2 Build: 26100.4061), but maybe one of you could confirm.

![Image](https://github.com/user-attachments/assets/877ac9fa-c505-4857-bbf1-3872339e852d)

Thanks and cheers.
