### ISSUE TITLE
Hi! I,m using tmdbv3api 1.6.2 and i can't get credits from a TV_show

### ISSUE THREAD

**Issue by josembw** [AnthonyBloomer/tmdbv3api#52]
I need the credits from the API GET Credits, GET /tv/{tv_id}/credits to get the cast an crew. But the app tmdbv3api 1.6.2 only have Season credits.  Is any work around to achieve that throw your tmdbv3api?

**Comment by BackrndSource** [comment]
In [details endpoint](https://developers.themoviedb.org/3/movies/get-movie-details) using [append_to_response](https://developers.themoviedb.org/3/getting-started/append-to-response)

in tmdbv3api the `credits` option is already added to `append_to_response `by default:

tmdbv3api/objs/tv.py:
```
def details(
        self, show_id, append_to_response="videos,trailers,images,credits,translations"
    ):
```
then try:
`tv = TV().details(123)`
or 
`tv = TV().details(123, 'credits')`

This will add two `dict `objects in attribute `tv.credits`. Accessing credits:
```
cast = tv.credits['cast']
crew = tv.credits['crew']
```
