### ISSUE TITLE
Hello I have an issue when i tray to get the credits from a Season 

### ISSUE THREAD

**Issue by josembw** [AnthonyBloomer/tmdbv3api#53]
I'm using tmdbv3api 1.6.2. When i try tu get from de API, GET /tv/{tv_id}/season/{season_number} thru def credits(self, tv_id, season_num):, from the tmdbv3api app, but i'm getting this error:

**The resource you requested could not be found**

Exception Type: | Exception
\lib\site-packages\tmdbv3api\tmdb.py, line 101, in _get_obj

Thanks for writing this helpful module!!

**Comment by BackrndSource** [comment]
season.credits is returning only cast, if there is not cast in response it return this error. I will solve it soon.

**Comment by BackrndSource** [comment]
Thank you!

**Comment by BackrndSource** [comment]
Solved in #83 
Thanks for report
