### ISSUE TITLE
Update tmdbv3api on the Python Package Index (PyPI)

### ISSUE THREAD

**Issue by meisnate12** [AnthonyBloomer/tmdbv3api#60]
Can you update tmdbv3api on the Python Package Index (PyPI) at https://pypi.python.org/pypi/tmdbv3api

**Comment by AnthonyBloomer** [comment]
Hello @meisnate12, [1.7.0](https://pypi.org/project/tmdbv3api/1.7.0/) has been published to PyPi.

**Comment by meisnate12** [comment]
Thank you so much!

**Comment by AnthonyBloomer** [comment]
You're welcome. Thank you for your great contributions! :)

**Comment by meisnate12** [comment]
so `network.py` and `serach.py` got added to PyPl but for some reason `trending.py` wasn't pushed with the others

**Comment by AnthonyBloomer** [comment]
Hey @meisnate12, sorry about that, I forgot to pull the latest changes before publishing. I've released [1.7.1](https://pypi.org/project/tmdbv3api/1.7.1/) which includes the Trending endpoint.

**Comment by meisnate12** [comment]
Awesome thanks I appreciate it!

**Comment by andy71** [comment]
I am not sure if it needs another new issue for that, but it seems that there is a difference again between the PyPi Version 1.7.6 and this GitHub Version. I cannot import Find, and the file objs/find.py is not in the version installed via pip.

**Comment by meisnate12** [comment]
I made my own tmdb library that does have find if you wanna use it   [TMDbAPIs](https://github.com/meisnate12/TMDbAPIs)
