### ISSUE TITLE
Travis CI enviroment variables

### ISSUE THREAD

**Issue by BackrndSource** [AnthonyBloomer/tmdbv3api#65]
All integrations tests are failing. 
@AnthonyBloomer can you put a encrypted enviroment variable for the TMDB_API_KEY in the .travis.yml?
More information:
https://docs.travis-ci.com/user/environment-variables/

**Comment by BackrndSource** [comment]
I added the TMDB_API_KEY variable to my fork. I've done it from https://travis-ci.com/. It works properly and I think it's better and easier than adding the key to the .travis.yml file.
The link above also explains.

**Comment by AnthonyBloomer** [comment]
Working on this.

**Comment by AnthonyBloomer** [comment]
@BackrndSource, thanks for creating this issue. I added the encrypted variable to the travis.yml. Previously it was added via the project settings in Travis CI. I believe having the encrypted variable in the travis.yml will mean the build will pick up the encryped variable across forks. Let me know how this works for you.

**Comment by BackrndSource** [comment]
I deleted my environment variable in my travis-ci account and created a pull request on my fork. He warns me that:

[One of the secure variables in your .travis.yml has an invalid format.]

And all tests fail.

I don't think it's going to work in the forks as this would compromise the security of your key. So for practical purposes it's the same to save the key in one place or another.

**Comment by AnthonyBloomer** [comment]
@BackrndSource, since you are a direct contributor to the project, rather than working off your fork, one workflow I was thinking of would be for you to create a branch directly on this repository and create pull requests that way? I think this would help with the failed builds and errors regarding missing environment variables when creating PRs that go through Travis.

**Comment by BackrndSource** [comment]
Good idea! I will do it like this, thanks!
