### ISSUE TITLE
HTTPS Endpoint?

### ISSUE THREAD

**Issue by burkasaurusrex** [AnthonyBloomer/tmdbv3api#70]
It looks like the base URL is using HTTP instead of HTTPS and then relying on TMDB to forward to HTTPS:

https://github.com/AnthonyBloomer/tmdbv3api/blob/514e37d81d4aa399fb73de65edc00c465205cd54/tmdbv3api/tmdb.py#L30

Anyway to change the base URL to HTTPS?

**Comment by AnthonyBloomer** [comment]
Hello @burkasaurusrex, thanks for creating this issue. This has been fixed in https://github.com/AnthonyBloomer/tmdbv3api/pull/71 and will be included in the next release.
