### ISSUE TITLE
how to get all the movies titles where country = turkey

### ISSUE THREAD

**Issue by HassanAbbas5** [AnthonyBloomer/tmdbv3api#79]
i want to get all the movies titles whose origin_country is turkey / India xyz

**Comment by BackrndSource** [comment]
https://developers.themoviedb.org/3/search/search-movies

**Comment by HassanAbbas5** [comment]
Kindly give an example with your library

**Comment by HassanAbbas5** [comment]
Get all the movies that are on netflix and are in turkey get all even if they are 10000+ how will you do it using your library

**Comment by BackrndSource** [comment]
Example is in examples/search_movies.py

You need to set your own search params, look at the link in the last comment. You can set country, but I think there is not posible to search by production company. You need to filter the results in your code.

Share it if you do it can be cool!

**Comment by BackrndSource** [comment]
Use discover endpoint. https://developers.themoviedb.org/3/discover/movie-discover

With the params `with_companies` and `region`. 
 

```
from tmdbv3api import Discover

discover = Discover()
params = {"region": "AAA", "with_companies": "Netflix"} 
result = discover.discover_movies(params) 
```
