### ISSUE TITLE
Get total number of pages when searching.

### ISSUE THREAD

**Issue by arvandf** [AnthonyBloomer/tmdbv3api#84]
When using search method (e.g. using `search.multi()`), I need to get total number of pages. How can I do this?

**Comment by BackrndSource** [comment]
total_pages is a property of TMDb Class.

```
tmdb = TMDb()

[... Your search.multi()...]

total_pages = tmdb.total_pages
# or
total_pages = os.environ['total_pages']
```

The data is stored as an environment variable. Look at code in `tmdbv3api/tmdb.py`
