### ISSUE TITLE
No function for "find external_id" in the package

### ISSUE THREAD

**Issue by adarshX** [AnthonyBloomer/tmdbv3api#89]
There is **no function to find the tmdbv id from an external id like IMDB id**. But the actual API has a get function for this known by "find external_id" ([here](https://developers.themoviedb.org/3/find/find-by-id)) 
So is it possible to add this function to this package?

Refer: https://developers.themoviedb.org/3/find/find-by-id

**Comment by meisnate12** [comment]
It's there its just not called find or anything like that heres how you can use it 

```python
import tmdbv3api

tmdbv3api.TMDb().api_key = "YOUR_API_KEY"
tmdbv3api.TMDb().language = "en"

# Gets external IDs using the TMDb ID (https://developers.themoviedb.org/3/movies/get-movie-external-ids)
print(tmdbv3api.Movie().external_ids(603))

# Gets a whole movie object from an External ID (https://developers.themoviedb.org/3/find/find-by-id)
print(tmdbv3api.Movie().external(external_id="tt0133093", external_source="imdb_id"))
```
using `tmdbv3api.Movie().external` with an imdb id for a tv show will still return the correct result with a show object under `tv_results`
